/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as CampusesIndexRouteImport } from './routes/campuses.index'
import { Route as StudyCourseIdRouteImport } from './routes/study.$courseId'
import { Route as CampusesCampusRouteImport } from './routes/campuses.$campus'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesIndexRoute = CampusesIndexRouteImport.update({
  id: '/campuses/',
  path: '/campuses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCourseIdRoute = StudyCourseIdRouteImport.update({
  id: '/study/$courseId',
  path: '/study/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesCampusRoute = CampusesCampusRouteImport.update({
  id: '/campuses/$campus',
  path: '/campuses/$campus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/campuses/$campus': typeof CampusesCampusRoute
  '/study/$courseId': typeof StudyCourseIdRoute
  '/campuses/': typeof CampusesIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/campuses/$campus': typeof CampusesCampusRoute
  '/study/$courseId': typeof StudyCourseIdRoute
  '/campuses': typeof CampusesIndexRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/campuses/$campus': typeof CampusesCampusRoute
  '/study/$courseId': typeof StudyCourseIdRoute
  '/campuses/': typeof CampusesIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/collaborate'
    | '/contact'
    | '/news'
    | '/campuses/$campus'
    | '/study/$courseId'
    | '/campuses/'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/collaborate'
    | '/contact'
    | '/news'
    | '/campuses/$campus'
    | '/study/$courseId'
    | '/campuses'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/collaborate'
    | '/contact'
    | '/news'
    | '/campuses/$campus'
    | '/study/$courseId'
    | '/campuses/'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CollaborateRoute: typeof CollaborateRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  CampusesCampusRoute: typeof CampusesCampusRoute
  StudyCourseIdRoute: typeof StudyCourseIdRoute
  CampusesIndexRoute: typeof CampusesIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/': {
      id: '/campuses/'
      path: '/campuses'
      fullPath: '/campuses/'
      preLoaderRoute: typeof CampusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$courseId': {
      id: '/study/$courseId'
      path: '/study/$courseId'
      fullPath: '/study/$courseId'
      preLoaderRoute: typeof StudyCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/$campus': {
      id: '/campuses/$campus'
      path: '/campuses/$campus'
      fullPath: '/campuses/$campus'
      preLoaderRoute: typeof CampusesCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CollaborateRoute: CollaborateRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  CampusesCampusRoute: CampusesCampusRoute,
  StudyCourseIdRoute: StudyCourseIdRoute,
  CampusesIndexRoute: CampusesIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
